version: '3.8'

services:
  web:
    build: ./web
    ports:
      - 80:80
    environment:
      KAFKA_SERVERS: kafka:9092
      CASSANDRA_SERVER: cassandra
      PYTHONUNBUFFERED: 1
    depends_on:
      - kafka
      - cassandra
    restart: always

  db_writer:
    build: ./db_writer
    environment:
      KAFKA_SERVERS: kafka:9092
      CASSANDRA_SERVER: cassandra
      PYTHONUNBUFFERED: 1
    depends_on:
      - kafka
      - cassandra
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=reviews

  cassandra-init:
    image: nuvo/docker-cqlsh
    volumes:
      - ./cassandra/setup.cql:/scripts/data.cql
    environment:
      - CQLSH_HOST=cassandra
      - CQLSH_PORT=9042
      - CQLVERSION=3.4.5
    depends_on:
      - cassandra
    restart: on-failure